### ISSUE TITLE
Generate .bin firmware for ESP32-2432S024C

### ISSUE THREAD

**Issue by Asmodeux2** [codekulturbonn/espocto#1]
Hey friend, you can compile the code and add the ready-to-install bin files for ESP32-2432S024C to the build folder in the repository. The community will be grateful, I assure you! 😊👍

**Comment by Asmodeux2** [comment]
Code compiled, ESP32-2432S024C not work

**Comment by Asmodeux2** [comment]
![20241109_221121.jpg](https://github.com/user-attachments/assets/959716a0-94a0-4ed8-8c4d-bae405a1ebfd)

**Comment by Asmodeux2** [comment]
I read the code and saw that without the SD card it does not initialize the display.

**Comment by oschettler** [comment]
Excellent idea. I have created [a prerelease](https://github.com/codekulturbonn/espocto/releases/tag/v0.1-pre1) and have also changed the code such that the missing SDcard is now signaled on the display.
